name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]  # 每天 0 点更新
  workflow_dispatch:              # 允许手动触发
  push: {branches: ["master", "main"]}  # 推送时触发

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories
          config_timezone: Asia/Hong_Kong
          plugin_languages: yes
          plugin_stargazers: yes
          plugin_followup: yes

  github-calendar:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

