name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]  # 每天 0 点更新
  workflow_dispatch:              # 允许手动触发
  push: {branches: ["master", "main"]}  # 推送时触发

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

